#pragma config(Sensor, in1,    lit,            sensorReflection)
#pragma config(Sensor, dgtl7,  sonarSensor,    sensorSONAR_mm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************************************************************
*
*  This file is meant as an introduction and as a template for developing
*  programs to run on the Vex controller.
*
*******************************************************************************/

/*******************************************************************************
*
*	main
*
*******************************************************************************/
task main() //define the main method
{
//  int bumper = 1;	              // normal bumper state = 1; when pressed = 0
int sensor_value; //created an instance variable for the sensor value



motor[leftMotor] = 127; //started the left motor at full speed
motor[rightMotor] = -127; //started the right motor at full speed

wait1Msec(2000);    					// give stuff time to turn on
while(true) //begin the loop
  {
  	motor[leftMotor] = 127; //made sure the motors are running
	motor[rightMotor] = -127;


    sensor_value = SensorValue[sonarSensor];
    if (sensor_value < 150) {
    	motor[leftMotor] = -127; //fullspeed backwards
	    motor[rightMotor] = 127; //fullspeed backwards
	    wait1Msec(1000);  // keep backing up for 1000ms (1 sec)

	    motor[leftMotor]  = 0;  //stop motors
	    motor[rightMotor] = 0;  //stop motors
	    wait1Msec(1000);
     }
  }
}
