#pragma config(Sensor, in1,    lit,            sensorReflection)
#pragma config(Sensor, in2,    lit2,           sensorReflection)
#pragma config(Sensor, in3,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl7,  sonarSensor,    sensorSONAR_mm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int sensor_value;
	int min = 1100;
	int minI = -127;
	while (true) {

	for(int i = -127;i < 127; i += 10)
		{
		motor[servoMotor] = i;
		wait1Msec(500);
		sensor_value = SensorValue[lit2];
		if (sensor_value < min) {
			min = sensor_value;
			minI = i;
		}
	}

  wait1Msec(1000);
	motor[servoMotor] = minI;
	wait1Msec(1000);
	motor[servoMotor] = minI;
	wait1Msec(1000);

	if (-20 < minI && minI < 20) {
		wait1Msec(1000);
		motor[leftMotor] = -127;
		motor[rightMotor] = 127;
		wait1Msec(3000);
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(1000);

	} else if (-127 < minI && minI < -20) {
		wait1Msec(1000);
		motor[leftMotor] = -127;
		motor[rightMotor] = 0;
		wait1Msec(-4.6875 * minI);
		writeDebugStreamLine("%f", -4.6875 * minI);
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(1000);

	} else {
			wait1Msec(1000);
			motor[leftMotor] = 0;
			motor[rightMotor] = 127;
			wait1Msec(4.6875 * minI);
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			wait1Msec(1000);
		}
	}
}
