#pragma config(Sensor, in1,    lit,            sensorReflection)
#pragma config(Sensor, in2,    lit2,           sensorReflection)
#pragma config(Sensor, in3,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl7,  sonarSensor,    sensorSONAR_mm)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  wait1Msec(1000);
	motor[servoMotor] = -100;
	wait1Msec(3000);
	motor[servoMotor] = -100;
	wait1Msec(30000);
}
