  #pragma config(Sensor, in7,    elbowpot,       sensorPotentiometer)
#pragma config(Sensor, in8,    shoulderpot,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  up,             sensorTouch)
#pragma config(Sensor, dgtl2,  down,           sensorTouch)
#pragma config(Sensor, dgtl3,  eup,            sensorTouch)
#pragma config(Sensor, dgtl4,  edown,          sensorTouch)
#pragma config(Sensor, dgtl5,  stopit,         sensorTouch)
#pragma config(Sensor, dgtl7,  sonar,          sensorSONAR_mm)
#pragma config(Sensor, dgtl9,  clawopen,       sensorTouch)
#pragma config(Sensor, dgtl10, clawclose,      sensorTouch)
#pragma config(Sensor, dgtl11, limit,          sensorTouch)
#pragma config(Motor,  port2,           shoulder,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           elbow,         tmotorVex393, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

short StopAll = false;
void clawOpen()
{

	motor[claw] = 127;

}
void clawClose()
{
	motor[claw] = -50;
}

void elbowDown(float x)
{
	while(SensorValue[elbowpot] < x) {
		motor[elbow] = 30;
	}
	motor[elbow] = 0;
}
void elbowUp()
{
	while(SensorValue[elbowpot] > 20) {
		motor[elbow] = -30;
	}
	motor[elbow] = 0;
}

void moveDown(float y)
{
		while(SensorValue[shoulderpot] > y){
			motor[shoulder] = -100;
		}
		motor[shoulder] = 0;
}

void moveUp()
{
		while(SensorValue[shoulderpot] < 1700){
			motor[shoulder] = 100;
		}
		motor[shoulder] = 0;
}

void finalPrgm()
{
	for (int i = 0; i < 3; i++) {
		int n = SensorValue[sonar];
		float x = -3.6441 * n + 3262.9;
		float y = -.917 * n + 1393.7;
		if (n > 436) {
			x = 1440;
			y = 893;
		}
		clawOpen();
		wait1Msec(500);
		elbowDown(x);
		moveDown(y);
		wait1Msec(500);
		clawClose();
		wait1Msec(500);
	  moveUp();
		elbowUp();
	  wait1Msec(500);
	  clawOpen();
	  wait1Msec(500);
	}
}





void failSafes()
{
	if(SensorValue[limit] == 1 || SensorValue[stopit] == 1){
		motor[shoulder] =0;
		wait1Msec(100);
		StopAll = true;
	}

}

void switches() {
	if (SensorValue[down] == 1){
			motor[shoulder] = -100;
		}
		if (SensorValue[up] == 1) {
			motor[shoulder] = 100;
		}
		if (SensorValue[edown] == 1) {
			motor[elbow] = 30;
		}
		if (SensorValue[eup] == 1) {
			motor[elbow] = -30;
		}
		if (SensorValue[clawopen] == 1) {
			motor[claw] = 127;
		}
		if (SensorValue[clawclose] == 1) {
			motor[claw] = -50;
		}
		if (SensorValue[stopit] == 1) {
			motor[shoulder] = 0;
			motor[elbow] = 0;
		}
	}

task main(){
	finalPrgm();
}//main
